PROMPTS=PROMPTS.concat([
{t:"Ladakh bike ride",c:"Travel India",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me on a motorcycle on a high Ladakh road with barren mountains, prayer flags and a deep blue sky, riding jacket and helmet on the tank, bright cold sunlight, adventure travel photo. 9:16."},
{t:"Manali snow day",c:"Travel India",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me playing in fresh snow in Manali in a warm jacket and beanie, pine trees heavy with snow, soft sunlight, a laughing candid moment. 9:16."},
{t:"Rishikesh bridge",c:"Travel India",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me standing on the Laxman Jhula bridge in Rishikesh at sunrise, the Ganga flowing below, soft mist, a simple kurta, a calm peaceful mood. 9:16."},
{t:"Rann of Kutch white desert",c:"Travel India",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me walking on the white salt desert of the Rann of Kutch at dusk, the endless white ground reflecting a pink and blue sky, a minimal outfit, a wide travel shot. 16:9."},
{t:"Munnar tea garden",c:"Travel India",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me among green tea gardens in Munnar on a misty morning, rolling hills, a light jacket, soft diffused light, a relaxed smile. 9:16."},
{t:"Andaman beach",c:"Travel India",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me on a clear turquoise Andaman beach with white sand and palm trees, a linen shirt, bright sunlight, a joyful vacation photo. 9:16."},
{t:"Hampi ruins sunrise",c:"Travel India",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me sitting on a boulder near the ancient Hampi ruins at sunrise, golden light on the stone temples, a thoughtful pose, a cinematic travel photo. 16:9."},
{t:"Udaipur lake palace",c:"Travel India",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me on a boat in Lake Pichola in Udaipur with the City Palace glowing at sunset behind me, a traditional kurta, soft golden reflections. 9:16."},
{t:"DSLR cinematic street portrait",c:"Trending Portraits",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Ultra-realistic DSLR portrait of me on a modern city street at blue hour in a premium oversized black t-shirt and a smartwatch, natural skin texture, cinematic orange and teal grade, 85mm f/1.2, soft bokeh lights, editorial quality. 4:5."},
{t:"Cyberpunk character",c:"Trending Portraits",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Turn me into a cyberpunk character in a rain-soaked neon city, a glowing visor and a techwear jacket, magenta and cyan reflections on wet streets, cinematic wide shot. 16:9."},
{t:"Retro purple saree",c:"Trending Portraits",p:"Use my uploaded photo as the face reference and keep my face exactly the same. A retro-style portrait of me in a purple chiffon saree with a soft film look, golden hour light, faded colours and gentle grain, like a 1970s movie still. 4:5."},
{t:"Radha Krishna devotional photo",c:"Trending Portraits",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. A respectful devotional portrait of me in simple traditional clothes sitting before a Radha Krishna idol in a flower-decorated temple, soft diya light, marigold garlands, a calm and peaceful mood. 9:16."},
{t:"Traditional portrait with bouquet",c:"Trending Portraits",p:"Use my uploaded photo as the face reference and keep my face exactly the same. An aesthetic portrait of me in a traditional outfit holding a fresh flower bouquet in a sunlit garden, soft pastel tones, a shallow depth of field and a gentle smile. 4:5."},
{t:"Bike and sunglasses cool look",c:"Trending Portraits",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Show me sitting casually on a sports bike with stylish sunglasses and a leather jacket, an evening city street with warm streetlights, a confident relaxed pose. 9:16."},
{t:"Mirror selfie 90s style",c:"Trending Portraits",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Create a 90s-style mirror selfie of me in a bedroom with posters on the wall, a flash glare on the mirror, baggy jeans and a graphic tee, slightly grainy colours. 9:16."},
{t:"Luxury watch ad portrait",c:"Trending Portraits",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Create a luxury watch ad portrait: me in a dark suit, a close crop on my wrist and watch with my face softly in the background, dramatic low-key light and a premium dark backdrop. 4:5."}
]);
