PROMPTS=PROMPTS.concat([
{t:"Couple caricature",c:"Couples & Wedding",p:"Using the two uploaded photos as face references (mine and my partner, with their consent), draw a funny big-head cartoon couple caricature in a bright comic style with [hobby 1] and [hobby 2] props. Square 1:1."},
{t:"Pre-wedding Rajasthan",c:"Couples & Wedding",p:"Using the two uploaded photos as face references, create a cinematic pre-wedding photo of us in traditional Rajasthani outfits in front of a golden fort at sunrise, walking hand in hand, warm tones. 9:16."},
{t:"Couple at Taj Mahal",c:"Couples & Wedding",p:"Using the two uploaded photos as face references, place us in front of the Taj Mahal at sunrise in matching soft colours, a romantic candid pose, a realistic travel photo. 9:16."},
{t:"Retro 80s couple",c:"Couples & Wedding",p:"Using the two uploaded photos as face references, turn us into an authentic 1980s Indian couple portrait with period outfits, studio flash and film grain. 4:5."},
{t:"Wedding mandap candid",c:"Couples & Wedding",p:"Using the two uploaded photos as face references, create a candid wedding photo of the couple laughing under a flower mandap, soft golden light and blurred guests around. 4:5."},
{t:"Anniversary poster",c:"Couples & Wedding",p:"Using the two uploaded photos as face references, design an anniversary poster with a heart-shaped floral frame, the text \"[years] years together\", soft pastel colours and elegant script. 4:5."},
{t:"Karva Chauth couple",c:"Couples & Wedding",p:"Using the two uploaded photos as face references, create a couple photo for Karva Chauth on a terrace at moonrise, a decorated thali and sieve, red outfits and warm lamp light. 9:16."},
{t:"Navratri Garba couple",c:"Couples & Wedding",p:"Using the two uploaded photos as face references, show us dancing Garba in matching chaniya choli and kediyu, spinning under string lights with a joyful motion blur. 9:16."},
{t:"Boy model studio shoot",c:"Model Photoshoot",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Create a professional model photoshoot of me in a black oversized shirt and trousers against a grey studio wall, hard side light, confident serious look, fashion magazine quality. 4:5."},
{t:"Cinematic urban overhead",c:"Model Photoshoot",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Shoot me from directly overhead standing on a city crosswalk, long shadow, street-style outfit, high contrast daylight, an editorial urban portrait. 9:16."},
{t:"Crimson overcoat portrait",c:"Model Photoshoot",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Portrait of me in a long crimson overcoat on a quiet autumn street, soft overcast light, falling leaves, a shallow depth of field, a stylish pose. 9:16."},
{t:"All-black suit portrait",c:"Model Photoshoot",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Portrait of me in an all-black suit with a high-collar shirt, dramatic low-key lighting, a smoky dark background and a sharp focus on the eyes. 4:5."},
{t:"Hairstyle poster front side back",c:"Model Photoshoot",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Create a hairstyle reference poster with three views of me: front, side and back. Style: [hairstyle], a clean grey background, soft even light, labels under each view. 3:4."},
{t:"Traditional saree portrait",c:"Model Photoshoot",p:"Use my uploaded photo as the face reference and keep my face exactly the same. A portrait of me in a [colour] silk saree with gold jewellery, soft window light, a calm elegant pose, a shallow depth of field and a realistic photo look. 4:5."}
]);
