PROMPTS=PROMPTS.concat([
{t:"Dance move loop",c:"Video Me",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Video of me doing a simple [dance step] in a bright studio, smooth continuous motion, loop-friendly ending, same face and outfit. 5 seconds, 9:16."},
{t:"Cinematic drone reveal",c:"Video Me",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Drone-style video starting high above and descending to reveal me standing alone on a mountain ridge, clouds moving below. 8 seconds, 16:9."},
{t:"Photo to old film clip",c:"Video Me",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Turn my photo into a vintage film clip: slight flicker, grain, soft sepia tones, gentle head movement and a warm smile. 5 seconds, 4:5."},
{t:"Endless image prompts",c:"Prompt Tools",p:"Act as an image prompt generator. Every time I type \"next\", give me one completely new, detailed image prompt about [topic]. Change the subject, location, lighting, camera angle, art style and colour palette each time, never repeat a previous prompt, and end with an aspect ratio."},
{t:"Endless video prompts",c:"Prompt Tools",p:"Act as a video prompt generator. Every time I type \"next\", give me one new AI video prompt about [topic]. Include subject, action, camera movement, lighting, style, duration and aspect ratio, and make each one different from all earlier ones."},
{t:"Endless prompts with my photo",c:"Prompt Tools",p:"Act as a prompt generator for pictures of me. Every time I type \"next\", write one new image prompt that starts with: Use my uploaded photo as the face reference and keep my face exactly the same. Then change the outfit, role, location, lighting and style each time, with no repeats."},
{t:"Surprise me with 10 prompts",c:"Prompt Tools",p:"Give me 10 very different AI prompts at once: 4 image prompts, 3 video prompts and 3 prompts using my uploaded photo as the face reference. Make every subject, setting and style unique, and label each prompt clearly."}
]);
