PROMPTS=PROMPTS.concat([
{t:"Hero entry video",c:"Bollywood Video",p:"Slow-motion video of a hero in a leather jacket and sunglasses walking out of smoke, sparks and dust flying, camera low and tracking backwards, orange light, mass-hero energy. Original characters only, no real actors, films or songs. 6 seconds, 16:9."},
{t:"Rain romance video",c:"Bollywood Video",p:"Video of a couple dancing slowly in heavy rain on a Mumbai street at night, glowing lamps, soft piano-like romantic mood, camera circling around them. Original characters only, no real actors, films or songs. 8 seconds, 16:9."},
{t:"Sangeet dance video",c:"Bollywood Video",p:"Video of a family dancing joyfully at a sangeet in colourful clothes, confetti falling, stage lights flashing, handheld party camera. Original characters only, no real actors, films or songs. 6 seconds, 9:16."},
{t:"Swiss mountain song video",c:"Bollywood Video",p:"Video of a couple running toward each other on a green Swiss meadow with snow peaks behind, soft focus glow, a 90s romantic song feel, a drone shot rising. Original characters only, no real actors, films or songs. 8 seconds, 16:9."},
{t:"Filmy dialogue closeup",c:"Bollywood Video",p:"Close-up video of a man delivering a dramatic filmy dialogue with a sharp stare, wind blowing his hair, thunder flash behind him, slow zoom in. Dialogue: \"[dialogue]\". Original characters only, no real actors, films or songs. 6 seconds, 9:16."},
{t:"Villain laugh video",c:"Bollywood Video",p:"Video of a villain in a white suit laughing slowly in a golden hall, the camera dollying in on his face, lightning flashing in the windows, dramatic score mood. Original characters only, no real actors, films or songs. 6 seconds, 16:9."},
{t:"Me hero entry video",c:"Bollywood Video",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Video of me making a slow-motion hero entry in a leather jacket and sunglasses through smoke, sparks behind me, low tracking camera. Original characters only, no real actors, films or songs. 6 seconds, 9:16."},
{t:"Me rain romance video",c:"Bollywood Video",p:"Use my uploaded photo as the face reference and keep my face and skin tone exactly the same. Video of me walking in the rain at night on a Mumbai street holding an umbrella, glowing lamps and a romantic cinematic mood, slow camera push-in. Original characters only, no real actors, films or songs. 6 seconds, 9:16."},
{t:"Filmy dialogues in Hinglish",c:"Filmy Writing",p:"Write 10 original dramatic filmy dialogues in Hinglish for a hero, 10 for a villain and 5 for a heroine. Keep each under 20 words, powerful and a little over the top, and do not copy any real movie dialogue."},
{t:"Movie trailer script",c:"Filmy Writing",p:"Write a 60-second Bollywood-style movie trailer voiceover for an original film called [title] in the [action / romance / comedy] genre. Include a hook, three big moments, a tagline and a release line. Keep characters and plot original."},
{t:"Original filmy song",c:"Filmy Writing",p:"Write an original Bollywood-style song in Hinglish about [theme] with a mukhda, two antaras and a chorus. Keep a catchy rhythm and an emotional feel, and avoid copying any existing song."},
{t:"Reel in Bollywood style",c:"Filmy Writing",p:"Give me 7 Reel ideas that recreate popular Bollywood movie moments in a funny everyday setting (office, college, home). For each write a 3-second hook, a short scene outline and a caption, using original dialogue."},
{t:"Bollywood quiz",c:"Filmy Writing",p:"Write a 15-question Bollywood quiz for Instagram with 4 options each, mixing easy and tough questions about eras, songs, directors and filmy trivia. Add the answer key at the end."},
{t:"Character backstory",c:"Filmy Writing",p:"Create an original Bollywood hero backstory for my short film: name, hometown, big dream, a painful past, a rival and a final twist. Keep it emotional and filmy, in 150 words."},
{t:"Poster title and tagline ideas",c:"Filmy Writing",p:"Give me 15 original Bollywood movie titles with a tagline for the [action / romance / comedy] genre. Make them catchy and avoid names of existing films."},
{t:"Bollywood caption pack",c:"Filmy Writing",p:"Write 20 Instagram captions in Hinglish with a filmy touch for [photo type], each under 15 words, with a fitting emoji. Do not copy lines from existing songs or films."}
]);
