PROMPTS=PROMPTS.concat([
{t:"Collectible action figure",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Turn me into a premium collectible action figure inside a plastic blister pack, friendly smile, recognisable features, standing upright. The pack header says \"[figure name]\" in large text with small accessories ([accessory 1], [accessory 2]) beside the figure."},
{t:"Chibi toy version",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Turn me into a 3D chibi-style collectible toy with a big head, small body, glossy plastic finish, my usual hairstyle and beard, on a clean shelf with soft studio light."},
{t:"Disposable camera memory",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Turn it into a faded late-90s disposable camera memory with dusty film grain, soft motion blur, uneven lighting, tiny scratches and a warm sunset glow leaking from one corner. Make it feel accidental and nostalgic. 4:5."},
{t:"Aged 90s Polaroid",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Age my photo like a forgotten 1990s Polaroid with a white border, slightly yellowed colours, fingerprints, faint creases and a handwritten date at the bottom."},
{t:"Scrapbook collage",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Make a handmade scrapbook page with torn notebook edges, handwritten notes, tape pieces, faded magazine cutouts and soft pastel textures, with my photo as the centre piece. 4:5."},
{t:"Y2K camcorder look",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Make it look like footage from an old camcorder: timestamp in the corner, slight CRT distortion, low resolution, direct flash, grainy colours and a playful candid pose."},
{t:"Fake movie poster",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Create a cinematic movie poster with me as the lead hero, dramatic lighting, title \"[title]\" in big letters, tagline \"[tagline]\" and a small credit block at the bottom. Original title only, no real actors or films. 2:3."},
{t:"History hopping",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Place me in [1920s ballroom / Mughal court / 1970s Mumbai street], with clothing, lighting and film texture matching that era so it looks like a real photo taken there. 4:5."},
{t:"Fun caricature",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Draw a vibrant caricature of me in bold comic-book style that highlights [my hobby] and [my funny habit], exaggerated expressions, thick outlines, bright colours."},
{t:"Motion on still photo",c:"Trending Now",p:"Bring my still photo to life: gentle wind in my hair and clothes, soft blinking, light flicker in the background, subtle parallax camera move, face stays exactly the same. 5 seconds, 9:16."},
{t:"Notes app quote card",c:"Trending Now",p:"Minimalist centred serif text \"[quote]\" in italic on a cream paper background, subtle paper grain, soft shadow, a pressed flower in the lower corner, Notes app screenshot aesthetic, slight angle. 4:5."},
{t:"Felt puppet version",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Transform me into a handcrafted felt puppet with visible stitching, soft fabric texture, button eyes, stop-motion aesthetic and warm studio lighting."},
{t:"Origami animal",c:"Trending Now",p:"An origami [animal] folded from paper, crisp creases, soft shadows, studio lighting on a plain [colour] background, macro detail, craft aesthetic. Square 1:1."},
{t:"4-panel story",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Make a 4-panel comic story with me as the same main character: panel 1 [scene 1], panel 2 [scene 2], panel 3 [scene 3], panel 4 [scene 4]. Same face and outfit in all panels, consistent art style."},
{t:"Ghibli-style scene",c:"Trending Now",p:"Use my uploaded photo as the face reference and keep my face exactly the same. Turn it into a soft hand-painted Ghibli-like scene: me sitting on a green hill with drifting clouds and wildflowers, gentle colours, dreamy light. 16:9."}
]);
