PROMPTS=PROMPTS.concat([
{t:"Diwali greeting poster",c:"Festival",p:"Diwali greeting poster with rows of glowing diyas, marigold garlands, rangoli and golden fireworks in a night sky. Leave clear space at the top for the text \"[greeting]\" and a small space at the bottom for [channel name]. Warm gold and deep blue colours, premium festive look. Vertical 9:16."},
{t:"Diwali rangoli and diyas",c:"Festival",p:"Top-down photo of a colourful rangoli with [pattern, e.g. lotus and peacock] surrounded by lit diyas and flower petals on the floor of a home entrance, warm glow, soft shadows, rich detail, festive and peaceful mood, 4K."},
{t:"Diwali family puja scene",c:"Festival",p:"Indian family in traditional clothes doing Lakshmi puja at home on Diwali night, glowing diyas, flowers and sweets on the thali, warm soft light, joyful and devoted faces, realistic cinematic photo, shallow depth of field, 16:9."},
{t:"Diwali Reel video",c:"Festival",p:"Vertical video: close-up of hands lighting a diya, camera slowly pulls back to reveal a decorated street full of lights and fireworks bursting in the sky, warm golden colours, gentle festive music mood, smooth motion, 8 seconds, 9:16."},
{t:"Holi colour portrait",c:"Festival",p:"Joyful portrait of a person laughing with colourful gulal powder flying in the air, pink, yellow, green and blue colours on face and clothes, bright daylight, freeze-motion, sharp focus on the eyes, vibrant festive mood, DSLR realism. Vertical 9:16."},
{t:"Holi greeting poster",c:"Festival",p:"Holi greeting poster with bursts of colour powder, pichkaris and water balloons, bright playful colours on a clean white background, empty space in the centre for the text \"[greeting]\", fun and happy style. Square 1:1."},
{t:"Holi slow-motion video",c:"Festival",p:"Slow-motion video of a handful of coloured gulal being thrown into the air, powder clouds spreading in bright sunlight, a smiling person in the background, rich saturated colours, shallow depth of field, 6 seconds, 9:16."},
{t:"Navratri Garba night",c:"Festival",p:"Garba night scene with people in colourful chaniya choli and kediyu dancing in a circle under string lights, spinning skirts, dandiya sticks, joyful energy, warm night glow, motion blur on the dancers, cinematic wide shot, 16:9."},
{t:"Nine Devi series",c:"Festival",p:"Write 9 image prompts, one for each form of Goddess Durga for the nine days of Navratri. For each give the name, her traditional colour for the day, vahana and symbols, and the setting. Keep a respectful traditional style, golden aura, and vertical 9:16 format."},
{t:"Ravan Dahan scene",c:"Festival",p:"Dussehra night scene: a giant Ravan effigy burning at an open ground with a huge crowd, sparks and fireworks in the sky, glowing orange light on the faces, cinematic wide shot, dramatic atmosphere, realistic photo, 16:9."},
{t:"Photo in festive outfit",c:"Festival",p:"Using my uploaded photo as the face reference, keep my face exactly the same and show me in a [festival] outfit (traditional kurta / sherwani) with festive lights and decorations in the background, natural lighting, realistic portrait, 8K. Vertical 9:16."},
{t:"Festival wishes in Hinglish",c:"Festival",p:"Write 10 short [festival] wishes in simple Hinglish for Instagram and WhatsApp status. Keep each under 20 words, warm and sweet in tone, with a suitable emoji, and no copied famous lines."},
{t:"Festival Shorts script",c:"Festival",p:"Write a 30-second Shorts script about the story and meaning of [festival] in simple Hinglish. Start with a 3-second hook, give 3 short facts, and end by asking viewers to comment their plans. Add an image prompt for each scene."},
{t:"Festival offer post",c:"Festival",p:"Write 3 festival offer post captions for [product or service] for [festival]. Include the offer ([offer]), the last date, a clear call to action, and 8 hashtags. Tone: friendly and festive."},
{t:"Festival content calendar",c:"Festival",p:"Plan 14 days of content for [festival] for my [niche] channel. For each day give the video or post idea, a title, and whether it is a Short, long video or story. Include a countdown post and a thank-you post."}
]);
